ingest:
  build: .
  volumes:
    - ../embed:/usr/local/src/hawk/
  environment:
    - C_FORCE_ROOT=true
    - REDIS_SERVER=media.embedr.eu
    - REDIS_PORT_NUMBER=6379
    - AWS_ACCESS_KEY_ID=
    - AWS_SECRET_ACCESS_KEY=
    - S3_CHUNK_SIZE=52428800
    - S3_HOST=s3.eu-central-1.amazonaws.com
    - S3_DEFAULT_BUCKET=storage.hawk.bucket
    - MAX_TASK_REPEAT=5
    - URL_OPEN_TIMEOUT=10
    - CLOUDSEARCH_REGION=eu-central-1
    - CLOUDSEARCH_ITEM_DOMAIN=hawk
    - CLOUDSEARCH_BATCH_DOMAIN=hawk-batch
  command: bash -c "celery --app=app.task_queue.task_queue worker -E -l info --workdir=/usr/local/src/hawk/ --autoscale=10,3 --hostname worker1.%h && celery --app=app.task_queue.task_queue worker -E -l info --workdir=/usr/local/src/hawk/ --autoscale=10,3 --hostname worker2.%h"
